import { z } from 'zod';
import type { AdapterRunResult, RewardComponent } from '../../domain/types';
import { BASE_USDC, decimal, liveOpportunity, ok, providerError, request, type LiveContext } from '../live';
const responseSchema=z.object({data:z.object({markets:z.object({items:z.array(z.unknown())})})});
const marketSchema=z.object({marketId:z.string().regex(/^0x[0-9a-fA-F]{64}$/),loanAsset:z.object({address:z.string()}),state:z.object({supplyApy:z.unknown().optional().nullable(),supplyAssetsUsd:z.unknown().optional().nullable(),liquidityAssetsUsd:z.unknown().optional().nullable(),utilization:z.unknown().optional().nullable(),rewards:z.array(z.unknown()).optional().nullable()})});
const rewardSchema=z.object({supplyApr:decimal,asset:z.object({address:z.string(),chain:z.object({id:z.number()})})});
const query=`query BaseUsdcMarkets { markets(first: 100, orderBy: SupplyAssetsUsd, orderDirection: Desc, where: { chainId_in: [8453], listed: true }) { items { marketId loanAsset { address } state { supplyApy supplyAssetsUsd liquidityAssetsUsd utilization rewards { supplyApr asset { address chain { id } } } } } } }`;
function optionalDecimal(value:unknown){if(value===null||value===undefined)return undefined;const parsed=decimal.safeParse(value);return parsed.success?parsed.data:undefined}
export async function fetchMorpho(ctx:LiveContext):Promise<AdapterRunResult>{const adapterId='morpho-blue-base',sourceId='morpho-graphql';try{const endpoint='https://api.morpho.org/graphql';const got=await request(ctx,endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query})});const payload=responseSchema.parse(got.json);const observations=[];let quarantined=0;for(const raw of payload.data.markets.items){const parsed=marketSchema.safeParse(raw);if(!parsed.success){quarantined++;continue}const x=parsed.data;if(x.loanAsset.address.toLowerCase()!==BASE_USDC)continue;const supplyApy=optionalDecimal(x.state.supplyApy),supplyAssetsUsd=optionalDecimal(x.state.supplyAssetsUsd);if(supplyApy===undefined||supplyAssetsUsd===undefined){quarantined++;continue}const rewards:RewardComponent[]=[];for(const rawReward of x.state.rewards??[]){const reward=rewardSchema.safeParse(rawReward);if(reward.success&&reward.data.asset.chain.id===8453)rewards.push({assetId:`eip155:8453/erc20:${reward.data.asset.address.toLowerCase()}`,apr:reward.data.supplyApr})}observations.push(liveOpportunity({protocolId:'morpho',protocolName:'Morpho Blue',sourceId,sourceName:'Morpho GraphQL',sourceUrl:endpoint,marketKey:x.marketId.toLowerCase(),name:'Morpho Blue USDC market',baseApy:supplyApy,tvlUsd:supplyAssetsUsd,liquidityUsd:optionalDecimal(x.state.liquidityAssetsUsd),utilization:optionalDecimal(x.state.utilization),rewards,rawHash:got.hash,at:ctx.at,link:`https://app.morpho.org/base/market/${x.marketId}`,confidence:'high'}))}const warnings=quarantined?[`${quarantined} Morpho row(s) quarantined because required identity, rate, or TVL was missing or invalid.`]:[];const result=ok(adapterId,sourceId,ctx.at,observations,got.hash,warnings);return {...result,counts:{seen:payload.data.markets.items.length,accepted:observations.length,quarantined,rejected:0}}}catch(e){const m=e instanceof Error?e.message:'Unknown provider error';return providerError(adapterId,sourceId,ctx.at,m==='Malformed JSON'?'malformed_json':m.startsWith('HTTP')?'http':'schema_drift',m)}}
