import Decimal from 'decimal.js';
import { z } from 'zod';
import type { AdapterRunResult } from '../../domain/types';
import { BASE_USDC, decimal, liveOpportunity, ok, providerError, request, type LiveContext } from '../live';
const market=z.object({asset:z.string(),assetAddress:z.string(),mToken:z.string(),deprecated:z.boolean(),baseSupplyApy:decimal,totalSupplyApr:decimal,totalSupplyUsd:decimal,liquidityUsd:z.number().finite().optional().nullable(),utilization:decimal.optional().nullable()}).passthrough();
const schema=z.object({data:z.array(z.unknown())});
const MOONWELL_RATE_UNIT='percent' as const;
function percentToRatio(value:string){return new Decimal(value).div(100).toString()}
export async function fetchMoonwell(ctx:LiveContext):Promise<AdapterRunResult>{const adapterId='moonwell-base',sourceId='moonwell-api';try{const endpoint='https://api.moonwell.fi/v1/markets?chain=base';const got=await request(ctx,endpoint,{headers:{'user-agent':'able-stable/0.1 (public yield catalog)'}});const payload=schema.parse(got.json);const observations=[];let quarantined=0,negativeLiquidity=0;for(const raw of payload.data){const parsed=market.safeParse(raw);if(!parsed.success){quarantined++;continue}const x=parsed.data;if(x.deprecated||x.assetAddress.toLowerCase()!==BASE_USDC)continue;const liquidity=x.liquidityUsd===null||x.liquidityUsd===undefined||x.liquidityUsd<0?undefined:String(x.liquidityUsd);if(x.liquidityUsd!==null&&x.liquidityUsd!==undefined&&x.liquidityUsd<0)negativeLiquidity++;observations.push(liveOpportunity({protocolId:'moonwell',protocolName:'Moonwell',sourceId,sourceName:'Moonwell markets API',sourceUrl:endpoint,marketKey:x.mToken.toLowerCase(),name:'Moonwell native USDC market',baseApy:percentToRatio(x.baseSupplyApy),baseApr:percentToRatio(x.totalSupplyApr),tvlUsd:x.totalSupplyUsd,liquidityUsd:liquidity,utilization:x.utilization??undefined,rawHash:got.hash,at:ctx.at,confidence:'high'}))}const warnings=['Reward yield and action link are omitted until token addresses and an exact route validate.',`Moonwell ${MOONWELL_RATE_UNIT}-valued APY/APR fields are divided by 100.`,...(negativeLiquidity?[`${negativeLiquidity} Moonwell row(s) reported negative liquidity; liquidity is unavailable, not zero.`]:[]),...(quarantined?[`${quarantined} Moonwell row(s) quarantined during validation.`]:[])];const result=ok(adapterId,sourceId,ctx.at,observations,got.hash,warnings);return {...result,counts:{seen:payload.data.length,accepted:observations.length,quarantined,rejected:0}}}catch(e){const m=e instanceof Error?e.message:'Unknown provider error';return providerError(adapterId,sourceId,ctx.at,m==='Malformed JSON'?'malformed_json':m.startsWith('HTTP')?'http':'schema_drift',m)}}
