import { buildCatalog, buildLiveCatalog, allDemoOpportunities } from '../src/data/catalog';
import { assets, chains, coverage } from '../src/data/registry';
import { fetchMorpho } from '../src/ingestion/adapters/live-morpho';
import { fetchMoonwell } from '../src/ingestion/adapters/live-moonwell';
import { fetchAave } from '../src/ingestion/adapters/live-aave';
import { fetchDefiLlama } from '../src/ingestion/adapters/live-defillama';
import { unavailableNative } from '../src/ingestion/adapters/live-unavailable';
import type { Mode } from '../src/domain/types';
type QueueBinding={send(body:unknown):Promise<void>}; type QueueMessage<T>={body:T;ack():void;retry():void}; type MessageBatch<T>={messages:QueueMessage<T>[]}; type ExecutionContext={waitUntil(promise:Promise<unknown>):void}; type ScheduledEvent={scheduledTime:number};
type Bindings={DEMO_MODE?:string;ALLOWED_ORIGIN?:string;BASE_RPC_URL?:string;AAVE_BASE_DATA_PROVIDER?:string;COMPOUND_BASE_COMET?:string;INGESTION_QUEUE?:QueueBinding;DB?:unknown;EVIDENCE?:unknown};
const json=(body:unknown,status=200,origin='http://localhost:5173')=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':status<300?'public, max-age=60, stale-while-revalidate=240':'no-store','Access-Control-Allow-Origin':origin,'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});
async function liveCatalog(env:Bindings,mode:Mode){const at=new Date().toISOString(),ctx={fetcher:(input:RequestInfo|URL,init?:RequestInit)=>globalThis.fetch(input,init),at,rpcUrl:env.BASE_RPC_URL,aaveDataProvider:env.AAVE_BASE_DATA_PROVIDER,compoundComet:env.COMPOUND_BASE_COMET};const tasks=[fetchAave(ctx),fetchMorpho(ctx),fetchMoonwell(ctx),fetchDefiLlama(ctx),Promise.resolve(unavailableNative('compound-iii-base','compound-rpc',at,env.BASE_RPC_URL&&env.COMPOUND_BASE_COMET?'Configured Comet deployment still requires independent verification before reads are enabled.':'BASE_RPC_URL and COMPOUND_BASE_COMET are required for authoritative Compound reads.')),Promise.resolve(unavailableNative('seamless-base','seamless-native',at,'Seamless native source and current operational status are not validated; advisory fallback requires exact identity and link.'))];const settled=await Promise.allSettled(tasks);const runs=settled.map((x,i)=>x.status==='fulfilled'?x.value:unavailableNative(`adapter-${i}`,'unknown-provider',at,'Adapter rejected outside its provider boundary.'));return buildLiveCatalog(mode,runs,at)}
async function route(request:Request,env:Bindings){const url=new URL(request.url),origin=env.ALLOWED_ORIGIN??'http://localhost:5173',demo=env.DEMO_MODE==='true';if(request.method!=='GET')return json({error:'Method not allowed'},405,origin);if(url.pathname==='/health')return json({ok:true,mode:demo?'fixture':'live',checkedAt:new Date().toISOString()},200,origin);if(url.pathname==='/v1/catalog'){const raw=url.searchParams.get('mode'),mode:Mode=raw==='degen'||raw==='cefi'?raw:'core';if(!demo&&(mode!=='core'||(url.searchParams.get('chain')??'base')!=='base'||(url.searchParams.get('asset')??'usdc')!=='usdc'))return json({error:'Live coverage unavailable',supported:'mode=core&chain=base&asset=usdc'},422,origin);const body=demo?buildCatalog(mode):await liveCatalog(env,mode);return json(body,body.status==='unavailable'?503:body.status==='partial'?206:200,origin)}if(url.pathname==='/v1/assets')return json({assets},200,origin);if(url.pathname==='/v1/chains')return json({chains},200,origin);if(url.pathname==='/v1/protocols')return json({coverage},200,origin);if(url.pathname==='/v1/status')return json({state:demo?'cached':'live-request',mode:demo?'fixture':'live',notice:demo?'DEMO_MODE=true; no providers are called.':'Each catalog request calls isolated providers; inspect catalog.adapters for per-source state.'},200,origin);if(url.pathname==='/v1/methodology')return json({principles:['Native sources first','Canonical identity, never symbol joins','No silent zero or empty-success fallbacks','Exact links only after identity verification','DeFiLlama is advisory only'],demoMode:demo},200,origin);const match=url.pathname.match(/^\/v1\/opportunities\/([^/]+)(\/history)?$/);if(match&&demo){const item=allDemoOpportunities().find(x=>x.id===decodeURIComponent(match[1]));if(!item)return json({error:'Opportunity unavailable'},404,origin);return json(match[2]?{opportunityId:item.id,observations:[{at:item.evidence.retrievedAt,baseApr:item.baseApr,baseApy:item.baseApy,demo:true}]}:item,200,origin)}return json({error:'Not found'},404,origin)}
export default {fetch:route,scheduled:async(_event:ScheduledEvent,env:Bindings,ctx:ExecutionContext)=>{if(env.INGESTION_QUEUE)ctx.waitUntil(Promise.all(['aave','morpho','compound','moonwell','defillama'].map(adapterId=>env.INGESTION_QUEUE!.send({adapterId,requestedAt:new Date().toISOString()}))))},queue:async(batch:MessageBatch<{adapterId:string}>)=>{for(const message of batch.messages)message.body.adapterId?message.ack():message.retry()}};
